//! Wire messages of the relay backend protocol, shared between the
//! `localsend` crate and the `server` binary.

use crate::model::discovery::DeviceType;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Information a device announces about itself to the relay backend. A subset
/// of the v2 `RegisterDtoV2`, without the address-dependent fields.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RelayDeviceInfo {
    /// The display name of the device.
    pub alias: String,

    /// Protocol version (major.minor) implemented by the device.
    pub version: String,

    /// Device model (e.g. "Samsung", "Windows").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_model: Option<String>,

    /// Device type category.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_type: Option<DeviceType>,

    /// Fingerprint identifying the device, as in the v2 protocol.
    pub fingerprint: String,

    /// The SHA-256 fingerprint (uppercase hex) of the device's TLS client
    /// certificate, when the device serves HTTPS. Peers use it to pin the
    /// connection before transferring data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cert_fingerprint: Option<String>,

    /// Whether the device's download API is active.
    #[serde(default)]
    pub download: bool,
}

/// A device registered with the backend, as it is announced to the other
/// devices in the same room.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RelayPeer {
    /// The ID the backend assigned to the device.
    pub client_id: Uuid,

    /// The device information it announced.
    pub info: RelayDeviceInfo,
}

/// A message sent by a device to the relay backend.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "type", rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RelayClientMessage {
    /// The first message sent on connect: joins the room `room`.
    Hello {
        /// The room key, derived from the room secret (see [`room_key`]).
        room: String,

        /// The information about this device.
        info: RelayDeviceInfo,
    },

    /// Updates the device information of the sender.
    Update { info: RelayDeviceInfo },

    /// Requests a relay session to `target_id`.
    Open {
        /// The session ID, generated by the sender.
        session_id: Uuid,

        /// The backend ID of the target device.
        target_id: Uuid,
    },

    /// Closes a relay session.
    Close { session_id: Uuid },
}

/// A message sent by the relay backend to a device.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "type", rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RelayServerMessage {
    /// The initial message sent to a device that just joined a room.
    Welcome {
        /// The ID the backend assigned to this device.
        client_id: Uuid,

        /// The other devices in the room.
        peers: Vec<RelayPeer>,
    },

    /// A new device joined the room.
    PeerJoined { peer: RelayPeer },

    /// A device updated its information.
    PeerUpdate { peer: RelayPeer },

    /// A device left the room.
    PeerLeft { peer_id: Uuid },

    /// The backend opened a relay session with this device: the other end
    /// wants to connect to it.
    Incoming {
        /// The session ID chosen by the initiator.
        session_id: Uuid,

        /// The device that opened the session.
        peer: RelayPeer,
    },

    /// The initiator of a session got the confirmation that the session was
    /// opened (the target was connected and notified).
    Opened { session_id: Uuid },

    /// A relay session was closed.
    Closed { session_id: Uuid },

    /// Error message.
    Error { code: u16 },
}

/// Derives the room key from the room secret: the hex-encoded SHA-256 of the
/// secret. The backend only ever sees the key, never the secret itself.
pub fn room_key(secret: &str) -> String {
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(secret.as_bytes());
    let mut hex = String::with_capacity(64);
    for byte in digest {
        hex.push_str(&format!("{byte:02x}"));
    }
    hex
}

/// The length of the header (a session ID) prefixed to every binary data frame.
pub const DATA_HEADER_LEN: usize = 16;

/// Serializes the payload of a relay session into the binary frame layout:
/// `[session_id (16 bytes)][payload]`.
pub fn encode_data(session_id: Uuid, payload: &[u8]) -> Vec<u8> {
    let mut frame = Vec::with_capacity(DATA_HEADER_LEN + payload.len());
    frame.extend_from_slice(session_id.as_bytes());
    frame.extend_from_slice(payload);
    frame
}

/// Splits a binary data frame back into its session ID and payload.
pub fn decode_data(frame: &[u8]) -> Option<(Uuid, &[u8])> {
    if frame.len() < DATA_HEADER_LEN {
        return None;
    }
    let mut bytes = [0u8; DATA_HEADER_LEN];
    bytes.copy_from_slice(&frame[..DATA_HEADER_LEN]);
    Some((Uuid::from_bytes(bytes), &frame[DATA_HEADER_LEN..]))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_room_key_is_stable_hex() {
        let a = room_key("hunter2");
        let b = room_key("hunter2");
        let c = room_key("hunter3");
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_eq!(a.len(), 64);
        assert!(a.chars().all(|ch| ch.is_ascii_hexdigit()));
    }

    #[test]
    fn test_data_roundtrip() {
        let session_id = Uuid::new_v4();
        let payload = b"hello relay";
        let frame = encode_data(session_id, payload);
        let (decoded_id, decoded_payload) = decode_data(&frame).unwrap();
        assert_eq!(decoded_id, session_id);
        assert_eq!(decoded_payload, payload);
        assert!(decode_data(&frame[..DATA_HEADER_LEN - 1]).is_none());
    }
}