// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/api/model.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'relay.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsRelayClient>>
abstract class RsRelayClient implements RustOpaqueInterface {
  /// The ID the backend assigned to this device, once connected.
  Future<String?> clientId();

  /// Emits [RsRelayEvent]s until the connection is lost or the client is
  /// stopped. Can only be listened to once.
  Stream<RsRelayEvent> listen();

  /// Opens a relay session to the device `target_id` for every connection
  /// accepted on a local TCP listener, and bridges the bytes between the two.
  /// Returns the local address to dial.
  ///
  /// This is how a relayed HTTP transfer is sent: the HTTP client connects
  /// to the returned address instead of the peer's real address, and the
  /// TLS handshake travels through the backend to the peer.
  Future<String> openProxy({required String targetId});

  /// Stops the client: closes the websocket and ends every session.
  Future<void> stop();

  /// Updates the announced device information.
  Future<void> updateInfo({required RsRelayInfo info});
}

@freezed
sealed class RsRelayEvent with _$RsRelayEvent {
  const RsRelayEvent._();

  /// The connection is established and this device has an ID.
  const factory RsRelayEvent.connected({
    required String clientId,
  }) = RsRelayEvent_Connected;

  /// A device joined the room, or is currently in the room (on connect).
  const factory RsRelayEvent.peer({
    required RsRelayPeer peer,
  }) = RsRelayEvent_Peer;

  /// A device updated its information.
  const factory RsRelayEvent.peerUpdate({
    required RsRelayPeer peer,
  }) = RsRelayEvent_PeerUpdate;

  /// A device left the room.
  const factory RsRelayEvent.peerLeft({
    required String peerId,
  }) = RsRelayEvent_PeerLeft;

  /// The connection was lost; the client must be reconnected.
  const factory RsRelayEvent.disconnected({
    String? error,
  }) = RsRelayEvent_Disconnected;
}

/// Information a device announces about itself to the relay backend.
///
/// A subset of the v2 `RegisterDtoV2`, without the address-dependent fields.
class RsRelayInfo {
  final String alias;
  final String version;
  final String? deviceModel;
  final DeviceType? deviceType;
  final String fingerprint;
  final String? certFingerprint;
  final bool download;

  const RsRelayInfo({
    required this.alias,
    required this.version,
    this.deviceModel,
    this.deviceType,
    required this.fingerprint,
    this.certFingerprint,
    required this.download,
  });

  @override
  int get hashCode =>
      alias.hashCode ^
      version.hashCode ^
      deviceModel.hashCode ^
      deviceType.hashCode ^
      fingerprint.hashCode ^
      certFingerprint.hashCode ^
      download.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsRelayInfo &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          version == other.version &&
          deviceModel == other.deviceModel &&
          deviceType == other.deviceType &&
          fingerprint == other.fingerprint &&
          certFingerprint == other.certFingerprint &&
          download == other.download;
}

/// A peer announced by the relay backend, as presented to this device.
/// A peer announced by the relay backend, as presented to this device.
class RsRelayPeer {
  final String clientId;
  final RsRelayInfo info;

  const RsRelayPeer({
    required this.clientId,
    required this.info,
  });

  @override
  int get hashCode => clientId.hashCode ^ info.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is RsRelayPeer && runtimeType == other.runtimeType && clientId == other.clientId && info == other.info;
}
